# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.26.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.26.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/Asta/Documents/prog/SF2 extract project/esf2"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/Asta/Documents/prog/SF2 extract project/esf2"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.26.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.26.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/Asta/Documents/prog/SF2 extract project/esf2/CMakeFiles" "/Users/Asta/Documents/prog/SF2 extract project/esf2//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/Asta/Documents/prog/SF2 extract project/esf2/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named esf2

# Build rule for target.
esf2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 esf2
.PHONY : esf2

# fast build rule for target.
esf2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/build
.PHONY : esf2/fast

src/esf2.o: src/esf2.c.o
.PHONY : src/esf2.o

# target to build an object file
src/esf2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/esf2.c.o
.PHONY : src/esf2.c.o

src/esf2.i: src/esf2.c.i
.PHONY : src/esf2.i

# target to preprocess a source file
src/esf2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/esf2.c.i
.PHONY : src/esf2.c.i

src/esf2.s: src/esf2.c.s
.PHONY : src/esf2.s

# target to generate assembly for a file
src/esf2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/esf2.c.s
.PHONY : src/esf2.c.s

src/filenameset.o: src/filenameset.c.o
.PHONY : src/filenameset.o

# target to build an object file
src/filenameset.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/filenameset.c.o
.PHONY : src/filenameset.c.o

src/filenameset.i: src/filenameset.c.i
.PHONY : src/filenameset.i

# target to preprocess a source file
src/filenameset.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/filenameset.c.i
.PHONY : src/filenameset.c.i

src/filenameset.s: src/filenameset.c.s
.PHONY : src/filenameset.s

# target to generate assembly for a file
src/filenameset.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/filenameset.c.s
.PHONY : src/filenameset.c.s

src/filewrite.o: src/filewrite.c.o
.PHONY : src/filewrite.o

# target to build an object file
src/filewrite.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/filewrite.c.o
.PHONY : src/filewrite.c.o

src/filewrite.i: src/filewrite.c.i
.PHONY : src/filewrite.i

# target to preprocess a source file
src/filewrite.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/filewrite.c.i
.PHONY : src/filewrite.c.i

src/filewrite.s: src/filewrite.c.s
.PHONY : src/filewrite.s

# target to generate assembly for a file
src/filewrite.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/filewrite.c.s
.PHONY : src/filewrite.c.s

src/iterators.o: src/iterators.c.o
.PHONY : src/iterators.o

# target to build an object file
src/iterators.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/iterators.c.o
.PHONY : src/iterators.c.o

src/iterators.i: src/iterators.c.i
.PHONY : src/iterators.i

# target to preprocess a source file
src/iterators.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/iterators.c.i
.PHONY : src/iterators.c.i

src/iterators.s: src/iterators.c.s
.PHONY : src/iterators.s

# target to generate assembly for a file
src/iterators.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/iterators.c.s
.PHONY : src/iterators.c.s

src/structfill.o: src/structfill.c.o
.PHONY : src/structfill.o

# target to build an object file
src/structfill.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/structfill.c.o
.PHONY : src/structfill.c.o

src/structfill.i: src/structfill.c.i
.PHONY : src/structfill.i

# target to preprocess a source file
src/structfill.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/structfill.c.i
.PHONY : src/structfill.c.i

src/structfill.s: src/structfill.c.s
.PHONY : src/structfill.s

# target to generate assembly for a file
src/structfill.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/structfill.c.s
.PHONY : src/structfill.c.s

src/verify.o: src/verify.c.o
.PHONY : src/verify.o

# target to build an object file
src/verify.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/verify.c.o
.PHONY : src/verify.c.o

src/verify.i: src/verify.c.i
.PHONY : src/verify.i

# target to preprocess a source file
src/verify.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/verify.c.i
.PHONY : src/verify.c.i

src/verify.s: src/verify.c.s
.PHONY : src/verify.s

# target to generate assembly for a file
src/verify.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/esf2.dir/build.make CMakeFiles/esf2.dir/src/verify.c.s
.PHONY : src/verify.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... esf2"
	@echo "... src/esf2.o"
	@echo "... src/esf2.i"
	@echo "... src/esf2.s"
	@echo "... src/filenameset.o"
	@echo "... src/filenameset.i"
	@echo "... src/filenameset.s"
	@echo "... src/filewrite.o"
	@echo "... src/filewrite.i"
	@echo "... src/filewrite.s"
	@echo "... src/iterators.o"
	@echo "... src/iterators.i"
	@echo "... src/iterators.s"
	@echo "... src/structfill.o"
	@echo "... src/structfill.i"
	@echo "... src/structfill.s"
	@echo "... src/verify.o"
	@echo "... src/verify.i"
	@echo "... src/verify.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

